apiVersion: v1
kind: Service
metadata:
  name: dotnet-rest-api
  labels:
    app: dotnet-rest-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: dotnet-rest-api